import { setupProject } from "../../viz_controller.js";

import { colors } from "../../helper_functions/colors.js";


let variables = {
	state_id: {"variable":"state_id", "displayName":"State Id", "format": "number", "scaleType":"quantize", "customRange":[colors.white, colors.blue.light, colors.blue.dark], "numBins":5},
	state: {"variable":"state", "displayName":"State", "format": "string"},
	state_abbrev: {"variable":"state_abbrev", "displayName":"State", "format": "string"},
	min_ed_requirement: {"variable":"min_ed_requirement", "displayName":"Minimum Educational Requirement", "format": "string", "category":"Principals", "scaleType":"categorical", "customDomain":["Bachelor's Degree", "Post-BA Degree or Coursework", "Master's Degree", "Post-MA Degree or Coursework"], "customRange": [colors.turquoise.very_light, colors.turquoise.light, colors.turquoise.medium, colors.turquoise.dark]},
	license_grade_span: {"variable":"license_grade_span", "displayName":"License Grade Span", "format": "string", "category":"Principals", "scaleType":"categorical", "canSplitCategory":true, "customDomain":["Elementary school principal license", "K-12 principal license", "PreK-12 principal license", "Varies based on program"], "customRange":[colors.turquoise.light, colors.blue.medium, colors.purple.medium, colors.grey.medium]},
	higher_ed_coursework: {"variable":"higher_ed_coursework", "displayName":"ECE Coursework", "format": "string", "category":"Principals", "scaleType":"categorical", "canSplitCategory":true, "customDomain":["Must Offer Early Learning Coursework","Must Offer Child Development Coursework", "No", "No data"], "customRange":[colors.turquoise.light, colors.blue.medium, colors.red.medium, colors.grey.light]},
	clinical_experience: {"variable":"clinical_experience", "displayName":"Clinical Experience Requirement", "format": "string", "category":"Principals", "scaleType":"categorical", "customDomain":["Yes", "No"], "customRange":[colors.turquoise.medium, colors.red.medium]},
	prior_teaching_experience: {"variable":"prior_teaching_experience", "displayName":"Teaching Experience Requirement", "format": "string", "category":"Principals", "scaleType":"categorical", "customDomain":["Yes", "No"], "customRange":[colors.turquoise.medium, colors.red.medium]},
	professional_learning: {"variable":"professional_learning", "displayName":"ECE Professional Learning", "format": "string", "category":"Principals", "scaleType":"categorical", "customDomain":["Yes", "No", "No data"], "customRange":[colors.turquoise.medium, colors.red.medium, colors.grey.light]},
	joint_professional_learning: {"variable":"joint_professional_learning", "displayName":"Joint Professional Learning", "format": "string", "category":"Principals", "scaleType":"categorical", "customDomain":["Yes", "No", "No data"], "customRange":[colors.turquoise.medium, colors.red.medium, colors.grey.light]},
	formal_evaluation: {"variable":"formal_evaluation", "displayName":"Formal Evaluation", "format": "string", "category":"Principals", "scaleType":"categorical", "customDomain":["Yes", "No", "No data"], "customRange":[colors.turquoise.medium, colors.red.medium, colors.grey.light]},
	track_principal_turnover: {"variable":"track_principal_turnover", "displayName":"Track Principal Turnover", "format": "string", "category":"Principals", "scaleType":"categorical", "customDomain":["Yes", "Yes (starting to)", "No", "No data"], "customRange":[colors.turquoise.medium, colors.turquoise.light, colors.red.medium, colors.grey.light]},
	avg_salary: {"variable":"avg_salary", "displayName":"Average Salary", "format": "price", "category":"Principals", "scaleType":"quantize", "customRange":[colors.white, colors.blue.light, colors.blue.dark], "numBins":5},
	benefits: {"variable":"benefits", "displayName":"Benefits", "format": "string", "category":"Principals", "scaleType":"categorical", "canSplitCategory":true, "customDomain":["Health Insurance, Pension/Retirement, and Paid Sick Leave", "Health Insurance and Pension/Retirement - No Paid Sick Leave", "Unknown/Data Not Available"], "customRange":[colors.turquoise.medium, colors.blue.medium, colors.grey.light]},
	diversity_incentives: {"variable":"diversity_incentives", "displayName":"Diversity Incentives", "format": "string", "category":"Principals", "scaleType":"categorical", "canSplitCategory":true, "customDomain":["Financial Incentives", "Supports in Place", "No", "No data"], "customRange":[colors.turquoise.light, colors.blue.medium, colors.red.medium, colors.grey.light]},

	cd_min_ed_requirement: {"variable":"cd_min_ed_requirement", "displayName":"Minimum Educational Requirement", "format": "string", "category":"Center Directors"},
	cd_ed_training_requirement: {"variable":"cd_ed_training_requirement", "displayName":"Education & Training Requirement", "format": "string", "category":"Center Directors", "scaleType":"categorical", "customDomain":["No higher ed/training", "Less than CDA", "CDA", "Some college coursework", "AA", "AA plus coursework", "BA"], "customRange": [colors.red.medium, colors.turquoise.light, colors.turquoise.dark, colors.blue.medium, colors.purple.light, colors.purple.dark, colors.blue.dark]},
	cd_ed_training_requirement_source: {"variable":"cd_ed_training_requirement_source", "displayName":"Education & Training Requirement Source", "format": "string", "category":"Center Directors"},
	cd_prior_experience: {"variable":"cd_prior_experience", "displayName":"Prior Child Care Experience Requirement", "format": "string", "category":"Center Directors", "scaleType":"categorical", "customDomain":["Yes", "No"], "customRange": [colors.turquoise.medium, colors.red.medium]},
	cd_prior_experience_years: {"variable":"cd_prior_experience_years", "displayName":"Prior Child Care Experience Years", "format": "string", "category":"Center Directors"},
	cd_licensing_standard_qual_notes: {"variable":"cd_licensing_standard_qual_notes", "displayName":"Licensing Standard Qualifications", "format": "string", "category":"Center Directors"},
	cd_prior_experience_source: {"variable":"cd_prior_experience_source", "displayName":"Prior Experience Source", "format": "string", "category":"Center Directors"},
	cd_has_credential: {"variable":"cd_has_credential", "displayName":"Center Director Credential", "format": "string", "category":"Center Directors", "scaleType":"categorical", "customDomain":["Yes", "No"], "customRange": [colors.turquoise.medium, colors.red.medium]},
	cd_credential_required_for_licensing: {"variable":"cd_credential_required_for_licensing", "displayName":"Credential Required for Licensing", "format": "string", "category":"Center Directors", "scaleType":"categorical", "customDomain":["Yes", "No", "N/A"], "customRange": [colors.turquoise.medium, colors.red.medium, colors.grey.light]},
	cd_credential_source: {"variable":"cd_credential_source", "displayName":"Credential Source", "format": "string", "category":"Center Directors"},
	cd_qris_different_tiers: {"variable":"cd_qris_different_tiers", "displayName":"QRIS Ties to Different Tiers", "format": "string", "category":"Center Directors", "scaleType":"categorical", "customDomain":["Yes", "No", "N/A"], "customRange": [colors.turquoise.medium, colors.red.medium, colors.grey.light]},
	cd_qris_different_tiers_source: {"variable":"cd_qris_different_tiers_source", "displayName":"QRIS Tiers Source", "format": "string", "category":"Center Directors"},
	cd_qris_different_tiers_notes: {"variable":"cd_qris_different_tiers_notes", "displayName":"QRIS Tiers Notes", "format": "string", "category":"Center Directors"},
	cd_formal_evaluation: {"variable":"cd_formal_evaluation", "displayName":"Formal Evaluation", "format": "string", "category":"Center Directors", "scaleType":"categorical", "customDomain":["Yes", "No"], "customRange": [colors.turquoise.medium, colors.red.medium]},
	cd_formal_evaluation_source: {"variable":"cd_formal_evaluation_source", "displayName":"Formal Evaluation Requirement Source", "format": "string"},
	cd_avg_salary: {"variable":"cd_avg_salary", "displayName":"Average Salary", "format": "price", "category":"Center Directors", "scaleType":"quantize", "customRange":[colors.white, colors.blue.light, colors.blue.dark], "numBins":5},
	cd_avg_salary_source: {"variable":"cd_avg_salary_source", "displayName":"Average Salary Source", "format": "string", "category":"Center Directors"},
}

let vizSettingsList = [
	{
		id: "#early-ed-leaders__pre-service-map", 
		vizType: "topo_json_map",
		primaryDataSheet: "states",
		geometryType: "states",
		geometryVar: variables.state_id,
		stroke: {"color": colors.white, "width":"1", "opacity": "1", "hoverColor": colors.white, "hoverWidth": "3"},
		filterVars: [ variables.min_ed_requirement, variables.license_grade_span, variables.higher_ed_coursework, variables.clinical_experience, variables.prior_teaching_experience, variables.cd_ed_training_requirement, variables.cd_prior_experience, variables.cd_has_credential, variables.cd_credential_required_for_licensing],
		tooltipVars: [ variables.state, variables.min_ed_requirement, variables.license_grade_span, variables.higher_ed_coursework, variables.clinical_experience, variables.prior_teaching_experience, variables.cd_min_ed_requirement, variables.cd_ed_training_requirement, variables.cd_prior_experience, variables.cd_prior_experience_years, variables.cd_licensing_standard_qual_notes, variables.cd_has_credential, variables.cd_credential_required_for_licensing],
		legendSettings: {"orientation": "vertical-right", "showTitle": true},
		filterGroupSettings: {"hidden": false},
	},
	{
		id: "#early-ed-leaders__in-service-map", 
		vizType: "topo_json_map",
		primaryDataSheet: "states",
		geometryType: "states",
		geometryVar: variables.state_id,
		stroke: {"color": colors.white, "width":"1", "opacity": "1", "hoverColor": colors.white, "hoverWidth": "3"},
		filterVars: [ variables.professional_learning, variables.joint_professional_learning, variables.formal_evaluation, variables.cd_qris_different_tiers, variables.cd_qris_different_tiers_notes, variables.cd_formal_evaluation],
		tooltipVars: [ variables.state, variables.professional_learning, variables.joint_professional_learning, variables.formal_evaluation, variables.cd_qris_different_tiers, variables.cd_qris_different_tiers_notes, variables.cd_formal_evaluation],
		legendSettings: {"orientation": "vertical-right", "showTitle": true},
		filterGroupSettings: {"hidden": false},
	},
	{
		id: "#early-ed-leaders__retention-map", 
		vizType: "topo_json_map",
		primaryDataSheet: "states",
		geometryType: "states",
		geometryVar: variables.state_id,
		stroke: {"color": colors.white, "width":"1", "opacity": "1", "hoverColor": colors.white, "hoverWidth": "3"},
		filterVars: [ variables.track_principal_turnover, variables.avg_salary, variables.benefits, variables.cd_avg_salary],
		tooltipVars: [ variables.state, variables.track_principal_turnover, variables.avg_salary, variables.benefits, variables.diversity_incentives, variables.cd_avg_salary ],
		legendSettings: {"orientation": "vertical-right", "showTitle": true},
		filterGroupSettings: {"hidden": false},
	},
	{
		id: "#early-ed-leaders__min-ed-requirement", 
		vizType: "category_breakdown",
		primaryDataSheet: "states",
		dotSettings: { "width": 30, "offset": 5},
		filterVars: [ variables.min_ed_requirement ],
		labelVar: variables.state_abbrev,
		tooltipVars: [ variables.state ],
	},
	{
		id: "#early-ed-leaders__license-grade-span", 
		vizType: "category_breakdown",
		primaryDataSheet: "states",
		dotSettings: { "width": 30, "offset": 5},
		filterVars: [ variables.license_grade_span ],
		labelVar: variables.state_abbrev,
		tooltipVars: [ variables.state ],
	},
	{
		id: "#early-ed-leaders__higher-ed-coursework", 
		vizType: "category_breakdown",
		primaryDataSheet: "states",
		dotSettings: { "width": 30, "offset": 5},
		filterVars: [ variables.higher_ed_coursework ],
		labelVar: variables.state_abbrev,
		tooltipVars: [ variables.state ],
	},
	{
		id: "#early-ed-leaders__clinical-experience", 
		vizType: "category_breakdown",
		primaryDataSheet: "states",
		dotSettings: { "width": 30, "offset": 5},
		filterVars: [ variables.clinical_experience ],
		labelVar: variables.state_abbrev,
		tooltipVars: [ variables.state ],
	},
	{
		id: "#early-ed-leaders__prior-teaching-experience", 
		vizType: "category_breakdown",
		primaryDataSheet: "states",
		dotSettings: { "width": 30, "offset": 5},
		filterVars: [ variables.prior_teaching_experience ],
		labelVar: variables.state_abbrev,
		tooltipVars: [ variables.state ],
	},
	{
		id: "#early-ed-leaders__professional-learning", 
		vizType: "category_breakdown",
		primaryDataSheet: "states",
		dotSettings: { "width": 30, "offset": 5},
		filterVars: [ variables.professional_learning ],
		labelVar: variables.state_abbrev,
		tooltipVars: [ variables.state ],
	},
	{
		id: "#early-ed-leaders__joint-professional-learning", 
		vizType: "category_breakdown",
		primaryDataSheet: "states",
		dotSettings: { "width": 30, "offset": 5},
		filterVars: [ variables.joint_professional_learning ],
		labelVar: variables.state_abbrev,
		tooltipVars: [ variables.state ],
	},
	{
		id: "#early-ed-leaders__track-principal-turnover", 
		vizType: "category_breakdown",
		primaryDataSheet: "states",
		dotSettings: { "width": 30, "offset": 5},
		filterVars: [ variables.track_principal_turnover ],
		labelVar: variables.state_abbrev,
		tooltipVars: [ variables.state ],
	},
	{
		id: "#early-ed-leaders__benefits", 
		vizType: "category_breakdown",
		primaryDataSheet: "states",
		dotSettings: { "width": 30, "offset": 5},
		filterVars: [ variables.benefits ],
		labelVar: variables.state_abbrev,
		tooltipVars: [ variables.state ],
	},
	{
		id: "#early-ed-leaders__avg-salary", 
		vizType: "category_breakdown",
		primaryDataSheet: "states",
		dotSettings: { "width": 30, "offset": 5},
		filterVars: [ variables.avg_salary ],
		labelVar: variables.state_abbrev,
		tooltipVars: [ variables.state ],
	},

]

let projectSettings = {
	dataUrl: "https://na-data-projects.s3.amazonaws.com/data/edpolicy/early_ed_leaders.json",
	downloadDataLink: "https://docs.google.com/spreadsheets/d/1Ojj6gLytFubMwoAC95lWhqwjA1X8D-CKuf1wFWkgtQE/",
	dataSheetNames:["states"],
	vizSettingsList: vizSettingsList
}

setupProject(projectSettings);

	